wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.13
    start_time: 1658617923
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 15
      - 16
      4: 3.7.13
      5: 0.12.17
      8:
      - 2
      - 5
alpha:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 256
dataset:
  desc: null
  value: dataset/pyg_data/icdm2022_session1.pt
device:
  desc: null
  value: cuda
early_stopping:
  desc: null
  value: 5
fanout:
  desc: null
  value: 200
h_dim:
  desc: null
  value: 64
in_dim:
  desc: null
  value: 256
inference:
  desc: null
  value: false
json_file:
  desc: null
  value: pyg_pred_session1.json
labeled_class:
  desc: null
  value: item
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: RGPRGNN
n_bases:
  desc: null
  value: 8
n_epoch:
  desc: null
  value: 100
n_layers:
  desc: null
  value: 3
nni:
  desc: null
  value: false
test_file:
  desc: null
  value: dataset/icdm2022_session1_test_ids.txt
validation:
  desc: null
  value: true
wandb:
  desc: null
  value: true
